# **Kernel SVM vs Logistic Regression via Gradient Descent**

In [72]:
# Let us first import some modules for this problem
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

np.random.seed(1)

In [73]:
def sigmoid(z):
#     """
#     sigmoid function that maps inputs into the interval [0,1]
#     Your implementation must be able to handle the case when z is a vector (see unit test)
#     Inputs:
#     - z: a scalar (real number) or a vector
#     Outputs:
#     - trans_z: the same shape as z, with sigmoid applied to each element of z
#     """
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    trans_z = 1 / (1 + np.exp(-z))
    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    return trans_z

def logistic_regression(X, w):
#     """
#     logistic regression model that outputs probabilities of positive examples
#     Inputs:
#     - X: an array of shape (num_sample, num_features)
#     - w: an array of shape (num_features,)
#     Outputs:
#     - logits: a vector of shape (num_samples,)
#     """
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    logits = sigmoid(np.dot(X,w))
    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    return logits

# unit test
# sample inputs:
z = np.array([215, -108, 0, 0.32])
X = np.array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
              [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
              [1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
              [5.38816734e-01, 4.19194514e-01, 6.85219500e-01]])
w = np.array([0.20445225, 0.87811744, 0.02738759])

# sample outputs:
# out1 = sigmoid(z)
# out1 : [1.00000000e+00 1.24794646e-47 5.00000000e-01 5.79324252e-01]
# out2 = logistic_regression(X, w)
# out2 : [0.67212099 0.5481529  0.5871972  0.62176131]


In [74]:
out1 = sigmoid(z)
out2 = logistic_regression(X, w)
print(out1,out2)

[1.00000000e+00 1.24794646e-47 5.00000000e-01 5.79324252e-01] [0.67212099 0.5481529  0.5871972  0.62176131]


In [75]:
def linear_kernel(X):
#     """
#     a function that compute the Kernel Matrix K given X
#     the entry at the i-th row, j-th column is given by the dot product
#     between i, j  rows of data matrix X
#     Inputs:
#     - X: an array of shape (num_sample, num_features)
#     Output:
#     - K: an array of shape (num_sample, num_sample)
#     """
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    n = X.shape[0]
    linK = np.zeros(shape=(n,n))
    
    for i in range(n):
        for j in range(n):
            linK[i, j] = np.dot(X[i], X[j])
            
    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    
    return linK

X = np.array([[1,3,1],
              [1,0,1]])
print(linear_kernel(X))

[[11.  2.]
 [ 2.  2.]]


In [76]:
def gaussian_kernel(X, gamma = 1.0):
#     """
#     a function that compute the Kernel Matrix K given X
#     the entry at the i-th row, j-th column is given in the homework
#     Inputs:
#     - X: an array of shape (num_sample, num_features)
#     Output:
#     - K: an array of shape (num_sample, num_sample)
#     """
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    n = X.shape[0]
    gaussK = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            gaussK[i, j] = np.exp(-1*gamma*(np.linalg.norm((X[i]-X[j]), ord=2)**2))
    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    
    return gaussK

X = np.array([[1,1,1],
              [1,0,1]])
print(gaussian_kernel(X))

[[1.         0.36787944]
 [0.36787944 1.        ]]





**Please check notes for derivation of gradient of hinge loss**






In [77]:
def hinge_loss(K, w, y, lamda = 1.0):
#     """
#     a function that compute the SVM Hinge loss value for the given dataset (X, y) and parameter w;
#     It also returns the gradient of loss function w.r.t w
#     Here (X, y) can be a set of examples, not just one example.
#     Remember -- we always take the average (divide by size of dataset) while calculating loss, gradient etc. 
#     Inputs:
#     - X: an array of shape (num_sample, num_features)
#     - w: an array of shape (num_features,)
#     - y: an array of shape (num_sample,), it is the ground truth label of data X
#     Output:
#     - loss: a scalar which is the value of loss function for the given data and parameters
#     - grad: an array of shape (num_featues,), the gradient of loss 
#     """
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    nf = K.shape[1]
    n = K.shape[0]
    grad = np.zeros(nf)
    
    temp = np.zeros(n)
    
    for i in range(n):
        if 1-y[i]*np.matmul(w, K.T)[i] > 0:
            temp[i] = 1
        else:
            temp[i] = 0
    
    loss = (np.matmul(np.matmul(w, K.T), w)/2) + (lamda/n)*(np.sum(temp))
    
    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    return loss, grad
#unit test -- write your own unit by following other unit tests
X = np.array([[0.67046751, 0.41730480, 0.55868983],
              [0.14038694, 0.19810149, 0.80074457],
              [0.96826158, 0.31342418, 0.69232262],
              [0.87638915, 0.89460666, 0.08504421]])
w = np.array([0.03905478, 0.16983042, 0.8781425, 1 ])
Y = np.array([1, 1, 0, 1])

loss,grad = hinge_loss(gaussian_kernel(X), w, Y)
print(loss,grad)

1.9988814761367293 [0. 0. 0. 0.]


In [78]:
def logistic_loss(K, w, y, lamda = 1.0):
#     """
#     a function that compute the logistic loss value for the given dataset represented by the Kernel Matrix K and parameter w;
#     It also returns the gradient of loss function w.r.t w, 
#     Please watch Lecture 23, this is not the same as Homework 3
#     Remember -- we always take the average (divide by size of dataset) while calculating loss, gradient etc. 
#     Inputs:
#     - X: an array of shape (num_sample, num_features)
#     - w: an array of shape (num_features,)
#     - y: an array of shape (num_sample,), it is the ground truth label of data X
#     Output:
#     - loss: a scalar which is the value of loss function for the given data and parameters
#     - grad: an array of shape (num_featues,), the gradient of loss 
#     """
    # *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    
    #assume gaussian kernel or oth

    a = logistic_regression(K,w)
    
    num_train = K.shape[0]
    
    
    loss = -1/num_train * np.sum(y*np.log(a) + (1-y)*np.log(1-a))
    
    grad = np.dot(K.T, (a-y))/num_train
    
    # *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
    return loss, grad
#unit test
# You may use the unit given in Homework 3 (with linear kernel)
X = np.array([[0.67046751, 0.41730480, 0.55868983],
              [0.14038694, 0.19810149, 0.80074457],
              [0.96826158, 0.31342418, 0.69232262],
              [0.87638915, 0.89460666, 0.08504421]])
w = np.array([0.03905478, 0.16983042, 0.8781425 ])
Y = np.array([1, 1, 0, 1])

loss,grad = logistic_loss(X, w, Y)
print(loss,grad)


0.626238298577102 [-0.00483685 -0.09821878 -0.0080873 ]


In [79]:
#loss,grad = hinge_loss(K, w, y)
#loss, grad = logistic_loss(K, w, y)
#print(loss,grad) 
#grad should be of the same size of the size of w

In [80]:
# set up the code for this experiment
# set up code for this experiment
import pandas as pd
import numpy as np
import string
from collections import Counter
import matplotlib.pyplot as plt

%matplotlib inline

np.random.seed(1)



import urllib.request
import shutil

url = 'https://www.dropbox.com/s/tacy227l893y9r1/spambase.data?dl=1'
file_name = 'spambase.data'
with urllib.request.urlopen(url) as response, open(file_name, 'wb') as out_file:
    shutil.copyfileobj(response, out_file)

df = pd.read_csv(file_name,
                    sep=',',
                    header=None)
df.head()

0     1     2    3     4     5     6     7     8     9   ...    48  \
0  0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.00   
1  0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.00   
2  0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.01   
3  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   
4  0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.00   

      49   50     51     52     53     54   55    56  57  
0  0.000  0.0  0.778  0.000  0.000  3.756   61   278   1  
1  0.132  0.0  0.372  0.180  0.048  5.114  101  1028   1  
2  0.143  0.0  0.276  0.184  0.010  9.821  485  2259   1  
3  0.137  0.0  0.137  0.000  0.000  3.537   40   191   1  
4  0.135  0.0  0.135  0.000  0.000  3.537   40   191   1  

[5 rows x 58 columns]

In [81]:
# Make data matrix X from df.head()
hatX = df.to_numpy()
y = hatX[:, -1] # for last column
X = hatX[:, :-1] # for all but last column

In [82]:
print(hatX.shape)

(4601, 58)


### 1.2.2 Padding features (not for grading) {-}
As we did in Homework 2, to simplify the notation, we pad the input $x$ by inserting 1 to the **beginning** so that we can absorb the bias term into the parameter $w$.

The following code morphs the variable `digits.data` by concatenating 1 and features.

In [83]:
ones = np.ones(X.shape[0]).reshape(-1, 1)
X = np.concatenate((ones, X), axis=1)
print(X.shape)

(4601, 58)


### 1.2.3 Create training and test sets (not for grading) {-}
As we have practiced in our previous homework, we will use the `train_test_split()` method to partition the dataset into training and test sets. In this experiment, we use 80% data for training and the remaining 20% data for testing. To ensure your results are replicable, we will set the `random_state` argument of `train_test_split()` to **1**.

In [84]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=1)
print(f'The training set contains {X_train.shape[0]} examples.')
print(f'The testing set contains {X_test.shape[0]} examples.')

The training set contains 3680 examples.
The testing set contains 921 examples.


### 1.2.3 Feature Normalization (not for grading) {-}
Since, we have implemented the function `featureNormalization()` to normalize the features that have different scale, now, we will learn to use the built-in function `StandardScaler()` in `scikit-learn`. As we did in `featureNormalization()`, `StandardScaler()` returns standardized features by removing the mean and scaling to unit variance.
Please read through the [API documentation](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) for detailed instructions.

In [85]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

### Training the model with gradient descent 
Now after all the pre-processing, we can train a logisitic regression model with the training data.  It is quite straightforward to make predictions on test data by using the learned model. To simplify the task, when the probability of being positive is greater than 0.5, we classify the sample to 1. Otherwise, we classify it to 0.

In this part, we will train the model with gradient descent. After that, predict the label for test examples and compute the test accuracy. You may want to follow the procedures below to obtain the results:
+ Randomly initialize the parameter $w$ by `np.random.rand`.
+ Use gradient descent to update $w$ (number of iteration `num_iters` and learning rate `lr` are provided).
+ Plot the curve of the $\ell(w)$ value as a function of how many update steps have been taken (you need a variable to store the history of $\ell(w)$ values).
+ Compute and report the test accuracy on test set.

In [97]:
num_iters = 1000
lr = 0.1
count = 0.0
# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
w = np.random.rand(X_train.shape[1])
X_train = gaussian_kernel(X_train)
loss_list = []
for i in range(num_iters):
    loss, grad = hinge_loss(X_train, w, y_train)
    loss_list.append(loss)
    w = w - lr*grad
# plotting
plt.plot(np.arange(num_iters), loss_list)
plt.xlabel('iterations')
plt.ylabel('loss')
plt.show()
# testing
# pred = sigmoid(np.dot(X_test,w))
# for i in range(len(pred)):
#     if pred[i] > 0.5:
#         pred[i] = 1
#     else:
#         pred[i] = 0

# count = 0
# for i in range(len(pred)):
#     if pred[i] == y_test[i]:
#         count+=1
# print("test accuracy: ", count/len(pred))

# *****END OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****

KeyboardInterrupt: 

In [99]:
num_iters = [100,200,500,1000]
lr = [0.01, 0.1, 0.2, 0.5]

w = np.random.rand(X_train.shape[1])
# X_train = gaussian_kernel(X_train)
loss_list = []
for i in range(num_iters[1]):
    loss, grad = hinge_loss(X_train, w, y_train)
    loss_list.append(loss)
    w = w - lr[1]*grad

KeyboardInterrupt: 

Increasing the training size increases the effectiveness of the SVM and log-loss, same for the lr. Overall, the gaussian kernel is much more effective than the linear kernel.

The accuracies increase with number of iternations and learning rate. 1000 iterations and 0.2 lr

# **Q1 and Q2 on BB notes**